### ISSUE TITLE
Add views to Spectacles.json files using Cameras in the Revit model

### ISSUE THREAD

**Issue by bhowes-tt** [tt-acm/Spectacles.RevitExporter#12]
Nick caught this one - for whatever reason I thought htis was working already :\

![image](https://cloud.githubusercontent.com/assets/3171551/9522752/58f45cce-4ca4-11e5-92b9-919cfa46de3e.png)

**Comment by bhowes-tt** [comment]
Had a quick look ... it would seem that we can filter 3d views using the isPerspective property to find the cameras, and then export each one.

**Comment by anagpuyol** [comment]
Tested with imperial and metric models and it works. I'd like other to test it and give me feedback.

I also made sure it only exported the views when the checkbox is checked
