### ISSUE TITLE
Views from another open file included in active file's exported .json

### ISSUE THREAD

**Issue by bhowes-tt** [tt-acm/Spectacles.RevitExporter#17]
Interesting one!  When I have multiple (only two in my case) revit files open and I export the active one, I get the views from both open files.

Project 1:
![image](https://cloud.githubusercontent.com/assets/3171551/9962063/e5db95a4-5df1-11e5-9c08-804ad5c30dd8.png)
![image](https://cloud.githubusercontent.com/assets/3171551/9962131/41d038d8-5df2-11e5-950f-6019695b45e8.png)

Project 2:
![image](https://cloud.githubusercontent.com/assets/3171551/9962171/686629ee-5df2-11e5-8f99-d60cbcd7c203.png)
![image](https://cloud.githubusercontent.com/assets/3171551/9962236/aee015f6-5df2-11e5-82c9-c862a1d6c2c5.png)

**Comment by anagpuyol** [comment]
big fat :bug: I'll fix it

**Comment by anagpuyol** [comment]
I'm creating new lists for the views every time the command is run. This is working. Give it a test @bhowes-tt
