### ISSUE TITLE
Save-As window is huge!

### ISSUE THREAD

**Issue by mnaugle-tt** [tt-acm/Spectacles.RevitExporter#18]
When saving the json file, the window is full screen and you can not adjust its size.
Should be a more reasonable size.

**Comment by bhowes-tt** [comment]
'huge!'  is a relative term.  can you please post a screenshot?

Here's mine, and you can adjust it's size:
![image](https://cloud.githubusercontent.com/assets/3171551/9968683/ccdadf80-5e17-11e5-83da-547daa72e90a.png)

**Comment by mnaugle-tt** [comment]
mine is full screen and doesn't move.  
![image](https://cloud.githubusercontent.com/assets/3228216/9968770/52eff0ba-5e18-11e5-97d3-00631884aa51.png)

**Comment by anagpuyol** [comment]
MIne is like Ben's...

**Comment by mnaugle-tt** [comment]
I will rebuild the project and see if that fixes it.

**Comment by bhowes-tt** [comment]
@mnaugle-tt - we are calling the standard windows save as dialog - nothing fancy:
https://github.com/tt-acm/Spectacles.RevitExporter/blob/master/src/Spectacles.RevitExporter/Command.cs#L313

This must have something to do with your system...  Maybe try some of this stuff:
https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=save%20as%20window%20full%20screen

**Comment by mnaugle-tt** [comment]
:joy:  yeah my machine thanks for the google link found a fix there.
